version: '3.8'

services:
  postgres:
    image: postgres:17.3
    container_name: bd_diario_gastronomico
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - /home/barox/meus_projetos/diario-gastronomico-db/data:/var/lib/postgresql/data

volumes:
  postgres_data:
